version: '3'
services:
  postgres:
    container_name: postgres-db
    image: postgres:12.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=studentdb
    ports:
      - 5432:5432